### ISSUE TITLE
label toevoegen

### ISSUE THREAD

**Issue by KoopReynders** [Karima002/fix-the-flow-interactive-website-#11]
Je kan bij het hamburger-menu en bij het vergrootglas een label plaatsen. Dan geef je de gebruiker feedforward.

**Comment by Karima002** [comment]
Commit 3d4a6d8
- Feedforward toegepast door 'menu' en 'zoek vergrootglas' svg te labelen:

![image](https://github.com/user-attachments/assets/9897c06c-da74-4fea-bff3-7f58fb297424)

**Comment by KoopReynders** [comment]
Staan de labels voor zoeken en het menu op een lijn?
En zijn de letters even groot? Of? het lijkt alsof het label bij het vergrootglas niet helemaal in het midden staat.

XL screen
<img width="112" alt="image" src="https://github.com/user-attachments/assets/d83f2a05-4519-4c69-a8cb-7122dbeca17d" />

Small screen
<img width="540" alt="image" src="https://github.com/user-attachments/assets/996a12d7-5ee6-4eff-ab68-f9673bb74f26" />

**Comment by KoopReynders** [comment]
Ik zie nu ook dat het label op Small screen anders is dan op XL screen. Daar maak je geen gebruik van hoofdletters. Is het wel hetzelfde element? Dit soort stylen kan je beter consistent houden!

**Comment by Karima002** [comment]
Commit bc41729

### Op 1 lijn
De labels voor het zoeken en menu staan nu op 1 lijn
![image](https://github.com/user-attachments/assets/30163bb8-eea7-41e8-b8ef-020477e6dcd4)

### Lettergrootte & hoofdletters gelijk gemaakt
De lettergrootte & lettertype op small screen verschilden t.o.v. groot scherm. De labels voor beide schermen zijn nu gelijk. Label voor zoeken staat nu ook in 1 lijn met de ondertitel van de logo (op groot scherm)
![image](https://github.com/user-attachments/assets/d396ba60-a1d7-4b88-b4ae-3dc08c4819c9)

### Centreren vergrootglas
Ook het vergrootglas is nu gecentreerd met de label.
_Groot scherm_
![image](https://github.com/user-attachments/assets/5bc1d079-1729-4147-92c8-95a202719542)

_Klein scherm_
![image](https://github.com/user-attachments/assets/526e7736-c4f3-4c37-a320-ef14c6e32205)

Thanks voor de feedback!

**Comment by KoopReynders** [comment]
Goed bezig!
