### ISSUE TITLE
Nav element selecteren

### ISSUE THREAD

**Issue by KoopReynders** [Karima002/fix-the-flow-interactive-website-#12]
https://github.com/Karima002/fix-the-flow-interactive-website-/blob/4c1140ab6e841a21996c277dcc6924408ee59161/scripts/index.js#L10-L11

Je gebruikt het nav element in twee functies. 
Selecteren  van het element hoeft maar 1 keer als je het bovenin je script doet. Dan kun je het in twee functies gebruiken.

**Comment by Karima002** [comment]
Commit 6b93308
- Elementen worden nu 1 keer geselecteerd bovenaan in Javascript, zo voorkom ik herhaling in mijn code 
https://github.com/Karima002/fix-the-flow-interactive-website-/blob/a4f614ba9209f736641aa1111058946ec3aac905/scripts/index.js#L1-L4
