### ISSUE TITLE
classlist.toggle in plaats van classlist add

### ISSUE THREAD

**Issue by Jesse-L3** [Karima002/fix-the-flow-interactive-website-#5]
Hier is een voorbeeld van jules:

Zorg ervoor dat jij nav button ook zichtbaar blijft wanneer je hem opent. dan kan je er nog een keer op klikken om de nav te sluiten.
Je kan ook binnen je event listener een class geven een class geven die je hamburger icoon overzet naar een X

```javascript
// Selecteer in het document de class 'ham-menu' en 'off-screen-menu'.
const hamMenu = document.querySelector(".ham-menu");
const offScreenMenu = document.querySelector(".off-screen-menu");

// Aan hamMenu voeg je een event listener toe, dus als er wat gebeurt in dit gevallen klikken, dan ...
// dan wordt aan off-screen-menu de class 'active' getoggled. Dus aan en uit gezet.
hamMenu.addEventListener("click", () => {
  hamMenu.classList.toggle("active");
  offScreenMenu.classList.toggle("active");
});
```

**Comment by Karima002** [comment]
De nav kan nu worden geopend en gesloten met een button:


https://github.com/user-attachments/assets/9c113897-d600-41bd-99cd-d9eccaa6bd24

Ook heb ik classlist.toggle gebruikt in plaats van classlist.add:
https://github.com/Karima002/fix-the-flow-interactive-website-/blob/8267a070fcabe9daff62ff50b83dd3cab3545522/scripts/index.js#L10-L14
